-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "altitude" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "currentLat" DOUBLE PRECISION,
ADD COLUMN     "currentLng" DOUBLE PRECISION,
ADD COLUMN     "distance" DOUBLE PRECISION,
ADD COLUMN     "heading" DOUBLE PRECISION,
ADD COLUMN     "isDiverting" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "speed" INTEGER NOT NULL DEFAULT 850,
ADD COLUMN     "weatherStatus" TEXT NOT NULL DEFAULT 'CLEAR';
